### Numpy
Numpy is a fundamental library for scientific comouting in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structure. In this lesson, we will cover the basic of Numpy, focusing on arrays and vectorized operations.
 

In [2]:
import numpy as np

# create array using numpy
# create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [9]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes

arr=np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n",arr)
print("Shape:", arr.shape)
print("Number of Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype) # may vary
print("Item Size:", arr.itemsize, "bytes") ## May vary

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Size: 6
Data Type: int64
Item Size: 8 bytes


In [3]:
## Numpy Vectorized Operations
arr1=np.array([1, 2, 3])
arr2=np.array([4,5,6])

## Element wise addition
print(arr1+arr2)

## Element wise subtraction
print(arr1-arr2)

## Element wise multiplication
print(arr1*arr2)

## Element wise division
print(arr1/arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [3]:
## Unievrsal Function

arr=np.array([1,2,3,4])
## square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


In [5]:
## Slicing
arr=np.array([[1, 2, 3, 4], [ 5, 6,7, 8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
arr[1: ,2:]

array([[ 7,  8],
       [11, 12]])

In [8]:
arr[0:2 , 1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [9]:
arr[0:2 , 2:]

array([[3, 4],
       [7, 8]])

In [10]:
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [11]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [12]:
## statistical concepts-Normalization
## to have a mean of 0 and a standard deviation of 1
arr=np.array([1, 2, 3, 4, 5])

## calculate mean
mean=np.mean(arr)
## calculate standard deviation
std_dev=np.std(arr)

## Normalize the array
normalized_arr=(arr-mean)/std_dev
print("Normalized array: ", normalized_arr)


Normalized array:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [17]:
## Logical operations
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr[arr>5]

array([ 6,  7,  8,  9, 10])